version: '3.9'

services:
  postgresql:
    image: postgres:16.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=typescript
    volumes:
      - database_data:/var/lib/postgresql/data

  webapp:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 5000:5000
    links:
      - postgresql
    environment:
      - PGHOST=postgresql
      - PGDATABASE=typescript
      - PGUSER=postgres
      - PGPASSWORD=postgres

volumes:
  database_data:
    driver: local